version: '3.1'

services:

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - mobupay-db-data:/var/lib/postgresql/data

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    sysctls:
      net.core.somaxconn: 1024

volumes: 
  mobupay-db-data:
